# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-15 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20171015_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_pic',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='article_tag',
            name='article_id',
        ),
    ]
