# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20171015_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.article_pic'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.article_tag'),
        ),
    ]
