# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-15 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20171015_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_pic',
            old_name='article_id',
            new_name='article_pic_id',
        ),
    ]
