# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-17 09:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20171015_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
